app:
  name: "ATM"
  version: "2.0.0"

postgres:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "qwerty"

http:
  port: 8000

log:
  level: "debug"

sha:
  salt: "klwnrkmw;rlg[e'tk[]]"